spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pokeAPI

  codec:
    max-in-memory-size: 2MB
#resilience4j:
#  circuitbreaker:
#    instances:
#      aposta-api-circuit-breaker:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10000
#        slowCallDurationThreshold: 500
#        slowCallRateThreshold: 50
#        permittedNumberOfCallsInHalfOpenState: 3
